timeout 30
scanfor manual
textonly
showtools about,reboot,shutdown

menuentry "CE-OS Install" {
    icon /EFI/BOOT/icons/os_linux.png
    loader /ubuntu/vmlinuz
    initrd /ubuntu/initrd
    options "boot=casper iso-scan/filename=/UBUNTU.ISO autoinstall ds=nocloud\;s=/ce-os/autoinstall/ ---"
}

menuentry "Network Install" {
    icon /EFI/BOOT/icons/os_linux.png
    loader /ubuntu/vmlinuz
    initrd /ubuntu/initrd
    options "boot=casper iso-scan/filename=/UBUNTU.ISO autoinstall ds=nocloud\;s=/network-install/autoinstall/ ---"
}

menuentry "Ubuntu Live Installer" {
    icon /EFI/BOOT/icons/os_linux.png
    loader /ubuntu/vmlinuz
    initrd /ubuntu/initrd
    options "boot=casper iso-scan/filename=/UBUNTU.ISO ---"
}

menuentry "Clonezilla Live" {
    loader /live/vmlinuz
    initrd /live/initrd.img
    options "boot=live union=overlay username=user config components quiet noswap edd=on nomodeset locales=en_US.UTF-8 keyboard-layouts=us ocs_live_run=ocs-live-general ocs_live_extra_param= ocs_live_batch=no net.ifnames=0 nosplash noprompt fetch=/live/filesystem.squashfs"
}
